server:
  port: 1986
spring:
  application:
    name: cloud-service-consumer
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.101:1988/eureka/

feign:
  hystrix:
    enabled: true