server:
  port: 1986
spring:
  application:
    name: cloud-service-consumer
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.25.128:1988/eureka/,http://192.168.25.128:1987/eureka/

feign:
  hystrix:
    enabled: true