server:
  port: 1986
spring:
  application:
    name: cloud-service-consumer
  security:
    enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.25.128:1988/eureka/

feign:
  hystrix:
    enabled: false