server:
  port: 1986
spring:
  application:
    name: cloud-service-consumer
  security:
    enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1988/eureka/

security:
  basic:
    enabled: false
management:
  security:
    enabled: false