server:
  port: 1986
spring:
  application:
    name: cloud-service-consumer
  security:
    enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.101:1988/eureka/
# set hystrix timeout to 10 seconds in order to avoid the failure of requests in short time
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
security:
  basic:
    enabled: false
management:
  security:
    enabled: false